### ISSUE TITLE
Added feature idea: Water level in tanks changes shielding

### ISSUE THREAD

**Issue by seanth** [ec429/kpu_mod#2]
It would be nice to have it so parts that hold water provide shielding based on the amount of water in them. So, for example, a tank that hold 100L of water, but has only 50L would provide 0.5 shielding.

**Comment by ec429** [comment]
Yes, it would; and oddly enough I just started coding pretty much that about five minutes before seeing this.

(Actually my approach might be a bit more complicated than this, it'll need a bit of thought as to how to model it.)

**Comment by ec429** [comment]
To clarify a bit: currently, parts that don't have a ModuleKappaRayAbsorber have an effective absorpCoeff of (1-e^(-m/2))/2, where m is the total mass of the part including all resources.  So this will roughly already happen for parts without the module.

However, (a) there's currently no way to make a part that has shielding as well as an absorptive resource, and (b) per unit mass, water is no more effective as shielding than, say, a rocket motor.  So instead I'm going to have a per-resource 'shielding cross-section' coefficient, and compute absorpCoeff as the combination of shielding from the part's dry mass and contributions from all the resources stored in it.  I would put the formula I want to use, but it's complicated and GitHub doesn't support LaTeX :(

**Comment by seanth** [comment]
Cool. I won't pretend that I am an expert here, so I bow to your approach. Having said that, could you leverage the density of the resource in the part? The denser the material, the more effective it is at stopping the high energy particles, yes?

**Comment by ec429** [comment]
Now implemented; see commit 5507998.  Works on the assumption that resource "amounts" are volume, so take the cube root to give linear distance, multiply by the density and the resource's absorpCoeff, then feed that into a negative exponential function to get the survival rate.  Then absorption is 1 - (survival rate).
The reason for working in survival rate is because it's multiplicative; by computing survival rates for all the resources in the part (and one for the part's dry mass), then multiplying them all together, one obtains the survival rate for the part as a whole.
